export const SET_CART = 'SET_CART';
export const DELETE_CART = "DELETE_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"
export const SET_QUANTITY = "SET_QUANTITY"